module top_mif (
    input  wire clk,
    input  wire reset,

    output wire halted,
    output wire [7:0]  pc_debug,
    output wire [15:0] instr_debug,
    output wire        exec_state_debug
);

    wire [7:0]  instr_addr;
    wire [15:0] instr_data;

    assign pc_debug    = instr_addr;
    assign instr_debug = instr_data;

    // ============================================================
    // CPU Core
    // ============================================================
    cpu16_core cpu (
        .clk              (clk),
        .reset            (reset),

        .instr_addr       (instr_addr),
        .instr_data       (instr_data),

        .halted           (halted),
        .exec_state_debug (exec_state_debug)
    );

    // ============================================================
    // Quartus ROM IP
    //
    // This ROM should be generated by Quartus IP Catalog.
    // ROM size:
    //   256 words x 16 bits
    //
    // Initialization file:
    //   program.mif
    //
    // Expected ports:
    //   address : 8-bit input
    //   clock   : input clock
    //   q       : 16-bit output
    // ============================================================
    instruction_rom imem (
        .address (instr_addr),
        .clock   (clk),
        .q       (instr_data)
    );

endmodule